# Generated by Django 4.2.7 on 2024-02-01 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рассылки')),
                ('start_time', models.TimeField(default=datetime.time(11, 0), verbose_name='Время начала рассылки')),
                ('end_time', models.TimeField(default=datetime.time(13, 0), verbose_name='Время окончания рассылки')),
                ('mailing_periodicity', models.DurationField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в месяц', verbose_name='Переодичность рассылки')),
                ('mailing_status', models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', max_length=10, verbose_name='Статус рассылки')),
                ('client', models.ManyToManyField(to='client.clientdata', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('attempt_status', models.BooleanField(verbose_name='Статус попытки')),
                ('error_msg', models.TextField(verbose_name='Сообщение ошибки')),
                ('client', models.CharField(max_length=75, verbose_name='Клиент')),
                ('mailing_settings', models.CharField(max_length=75, verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('body_letter', models.TextField(verbose_name='Тело письма')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
