# Generated by Django 4.2.7 on 2024-02-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_periodicity',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', verbose_name='Переодичность рассылки'),
        ),
    ]
