# Generated by Django 4.2.7 on 2024-02-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_mailing_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_activ',
            field=models.BooleanField(default=False, verbose_name='Признак активной рассылки'),
        ),
    ]
