# Generated by Django 4.2.7 on 2024-02-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_is_activ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
